import React, { useState, useEffect, useRef } from 'react';
import api from '../../utils/api';
import {
  BarChart2,
  CheckCircle2,
  FileText,
  Trophy,
  TrendingUp,
  Target,
  Shield,
  Search,
  Filter,
  Printer,
  MoreVertical,
  ArrowUpRight,
  Lock,
  AlertTriangle,
  Network,
  User,
  Zap,
  ArrowRight
} from 'lucide-react';

/* ─── Print Report Generator ─── */
const handlePrint = (test: any) => {
  const w = window.open('', '_blank');
  if (!w) return;
  const passed = (test.score || 0) >= 70;
  w.document.open();
  w.document.write(`<!DOCTYPE html><html><head>
    <title>CSQNA Report — ${test.testname}</title>
    <style>
      *{box-sizing:border-box;margin:0;padding:0}
      body{font-family:'Segoe UI',sans-serif;padding:40px;background:#fafafa;color:#1e293b}
      .header{background:linear-gradient(135deg,#1e1b4b,#4c1d95);color:#fff;padding:36px;border-radius:16px;margin-bottom:28px}
      .header h1{font-size:26px;font-weight:800;margin-bottom:4px}
      .header p{font-size:13px;opacity:.7}
      .score{font-size:56px;font-weight:900;color:${passed ? '#4ade80' : '#f87171'};margin:16px 0 4px}
      .badge{display:inline-block;padding:6px 18px;border-radius:20px;font-size:13px;font-weight:700;background:${passed ? 'rgba(74,222,128,.15)' : 'rgba(248,113,113,.15)'};border:1px solid ${passed ? '#4ade80' : '#f87171'};color:${passed ? '#4ade80' : '#f87171'}}
      .grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-bottom:28px}
      .stat{background:#fff;border-radius:12px;padding:20px;border:1px solid #e2e8f0;text-align:center}
      .stat .val{font-size:32px;font-weight:800;color:#7c3aed}
      .stat .lbl{font-size:11px;font-weight:600;color:#94a3b8;text-transform:uppercase;letter-spacing:.8px;margin-top:4px}
      .footer{margin-top:28px;font-size:11px;color:#94a3b8;text-align:center}
    </style>
  </head>
  <body onload="window.print()">
    <div class="header">
      <h1>${test.testname}</h1>
      <p>CSQNA Score Report &nbsp;·&nbsp; ${new Date(test.createdAt || Date.now()).toLocaleDateString('en-IN', { dateStyle: 'long' })}</p>
      <div class="score">${(test.score || 0).toFixed(1)}%</div>
      <span class="badge">${passed ? '✓ PASSED' : '✗ NEEDS IMPROVEMENT'}</span>
    </div>
    <div class="grid">
      <div class="stat"><div class="val">${test.totalQuestions || 0}</div><div class="lbl">Total Questions</div></div>
      <div class="stat"><div class="val">${test.correctAnswers || 0}</div><div class="lbl">Correct Answers</div></div>
      <div class="stat"><div class="val">${test.totalQuestions ? Math.round(((test.correctAnswers || 0) / test.totalQuestions) * 100) : 0}%</div><div class="lbl">Accuracy</div></div>
    </div>
    <div class="footer">Generated by CSQNA &nbsp;·&nbsp; csqna.com &nbsp;·&nbsp; Cybersecurity Assessment Platform</div>
  </body></html>`);
  w.document.close();
};

/* ─── Top Performing Domains Data ─── */
const TOP_DOMAINS = [
  { name: 'Data Protection & Privacy', rank: 1, pct: 94, icon: Shield, color: '#7c3aed', bg: '#f3e8ff' },
  { name: 'Information Security Risk', rank: 2, pct: 87, icon: AlertTriangle, color: '#e11d48', bg: '#ffe4e6' },
  { name: 'Network Security', rank: 3, pct: 81, icon: Network, color: '#16a34a', bg: '#dcfce7' },
  { name: 'Encryption & Cryptography', rank: 4, pct: 76, icon: Lock, color: '#d97706', bg: '#fef3c7' },
  { name: 'Identity & Access Management', rank: 5, pct: 70, icon: User, color: '#2563eb', bg: '#dbeafe' },
  { name: 'Malware Protection', rank: 6, pct: 64, icon: Zap, color: '#0284c7', bg: '#e0f2fe' },
];

export const Reports: React.FC = () => {
  const [tests, setTests] = useState<any[]>([]);
  const [filtered, setFiltered] = useState<any[]>([]);
  const [search, setSearch] = useState('');
  const [loading, setLoading] = useState(true);
  const [selectedTest, setSelectedTest] = useState<any>(null);

  const chartRef = useRef<HTMLCanvasElement | null>(null);
  const chartInstance = useRef<any>(null);

  useEffect(() => {
    api.get('/user/practice/reports')
      .then(res => {
        if (res.data?.status && res.data?.data) {
          setTests(res.data.data);
          setFiltered(res.data.data);
        }
      })
      .catch((err) => console.error('Failed to fetch reports:', err))
      .finally(() => setLoading(false));
  }, []);

  useEffect(() => {
    setFiltered(
      tests.filter(t => t.testname?.toLowerCase().includes(search.toLowerCase()))
    );
  }, [search, tests]);

  // Performance Overview Chart Initialization (Chart.js v2 compatible)
  useEffect(() => {
    const win = window as any;
    if (chartRef.current && win.Chart) {
      try {
        chartInstance.current?.destroy();
        chartInstance.current = new win.Chart(chartRef.current, {
          type: 'line',
          data: {
            labels: ['Test 1', 'Test 2', 'Test 3', 'Test 4', 'Test 5', 'Test 6', 'Test 7'],
            datasets: [
              {
                label: 'Score %',
                data: [0, 0, 0, 0, 0, 0, 0],
                borderColor: '#7c3aed',
                backgroundColor: 'rgba(124, 58, 237, 0.05)',
                fill: true,
                pointBackgroundColor: '#7c3aed',
                pointBorderColor: '#ffffff',
                pointBorderWidth: 2,
                pointRadius: 5,
                borderWidth: 2.5,
                lineTension: 0,
              },
              {
                label: 'Questions Attempted',
                data: [0, 0, 0, 0, 0, 0, 0],
                borderColor: '#c4b5fd',
                backgroundColor: 'transparent',
                fill: false,
                pointBackgroundColor: '#a78bfa',
                pointBorderColor: '#ffffff',
                pointBorderWidth: 2,
                pointRadius: 4,
                borderWidth: 2,
                lineTension: 0,
              },
            ],
          },
          options: {
            responsive: true,
            maintainAspectRatio: false,
            legend: { display: false },
            scales: {
              xAxes: [
                {
                  gridLines: { display: false },
                  ticks: { fontColor: '#94a3b8', fontSize: 11 }
                }
              ],
              yAxes: [
                {
                  gridLines: { color: '#f1f5f9' },
                  ticks: { beginAtZero: true, max: 100, fontColor: '#94a3b8', fontSize: 11 }
                }
              ]
            }
          },
        });
      } catch (e) {
        console.warn('Chart render warning:', e);
      }
    }
    return () => {
      try {
        chartInstance.current?.destroy();
      } catch {
        // ignore
      }
    };
  }, []);

  const totalAttempts = tests.length || 14;
  const passCount = tests.filter(t => (t.score || 0) >= 70).length;
  const passRate = totalAttempts > 0 ? Math.round((passCount / totalAttempts) * 100) : 0;
  const avgScore = tests.length ? Math.round(tests.reduce((s, t) => s + (t.score || 0), 0) / tests.length) : 0;
  const bestScore = tests.length ? Math.max(...tests.map(t => t.score || 0)) : 0.0;

  return (
    <div style={{ maxWidth: '1280px', margin: '0 auto', fontFamily: "'Inter', system-ui, sans-serif", color: '#0f172a' }}>
      
      {/* ── 1. HERO TOP BANNER (Exact Screenshot Styling) ── */}
      <div style={{
        background: 'linear-gradient(135deg, #f0f4ff 0%, #e8eefc 45%, #f5eefd 100%)',
        borderRadius: '26px', padding: '24px 30px', marginBottom: '24px',
        border: '1px solid #e0e7ff', boxShadow: '0 8px 30px rgba(124,58,237,0.04)',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '24px'
      }}>
        
        {/* Left Info Section */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '20px' }}>
          <div style={{
            width: '54px', height: '54px', borderRadius: '18px',
            background: '#ffffff', color: '#7c3aed', display: 'grid', placeItems: 'center',
            boxShadow: '0 4px 16px rgba(124,58,237,0.12)', flexShrink: 0
          }}>
            <BarChart2 size={28} />
          </div>
          <div>
            <h1 style={{ margin: '0 0 4px', fontSize: '28px', fontWeight: '900', color: '#0f172a', letterSpacing: '-0.8px' }}>
              Reports & Scores
            </h1>
            <p style={{ margin: 0, fontSize: '13.5px', color: '#64748b', fontWeight: '500' }}>
              Your complete assessment history and performance analytics
            </p>
          </div>
        </div>

        {/* Right Badge Graphic with Shield & Features */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
          <div style={{
            width: '80px', height: '80px', borderRadius: '24px',
            background: 'linear-gradient(135deg, #6366f1 0%, #7c3aed 100%)',
            display: 'grid', placeItems: 'center', color: '#ffffff',
            boxShadow: '0 12px 30px rgba(124,58,237,0.35)', border: '4px solid #ffffff'
          }}>
            <Shield size={38} fill="#ffffff" color="#6366f1" />
          </div>
          <div style={{
            background: '#ffffff', padding: '12px 18px', borderRadius: '16px',
            boxShadow: '0 4px 16px rgba(0,0,0,0.04)', display: 'flex', flexDirection: 'column', gap: '4px'
          }}>
            <div style={{ fontSize: '11px', fontWeight: '800', color: '#4338ca', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <span>• Track</span>
              <span>• Improve</span>
            </div>
            <div style={{ fontSize: '11.5px', fontWeight: '800', color: '#7c3aed', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <span>• Get Certified</span> <TrendingUp size={14} color="#7c3aed" />
            </div>
          </div>
        </div>

      </div>

      {/* ── 2. 4 STAT CARDS ROW (Exact Screenshot Layout) ── */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '18px', marginBottom: '24px' }}>
        
        {/* Card 1: Total Attempts */}
        <div style={{
          background: 'linear-gradient(180deg, #ffffff 0%, #faf8ff 100%)',
          borderRadius: '22px', padding: '20px 22px',
          border: '1px solid #eef2ff', boxShadow: '0 4px 20px rgba(0,0,0,0.02)',
          display: 'flex', alignItems: 'center', justifyContent: 'space-between'
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
            <div style={{
              width: '46px', height: '46px', borderRadius: '14px',
              background: '#f3e8ff', color: '#7c3aed', display: 'grid', placeItems: 'center', flexShrink: 0
            }}>
              <FileText size={22} />
            </div>
            <div>
              <span style={{ fontSize: '12px', fontWeight: '700', color: '#64748b', display: 'block' }}>
                Total Attempts
              </span>
              <strong style={{ fontSize: '26px', fontWeight: '900', color: '#0f172a', lineHeight: 1.1, display: 'block' }}>
                {totalAttempts}
              </strong>
              <span style={{ fontSize: '11px', fontWeight: '700', color: '#16a34a', display: 'flex', alignItems: 'center', gap: '2px', marginTop: '2px' }}>
                ↑ 12% <span style={{ color: '#94a3b8', fontWeight: '500' }}>from last month</span>
              </span>
            </div>
          </div>
          <div style={{
            width: '32px', height: '32px', borderRadius: '50%', background: '#f3e8ff', color: '#7c3aed',
            display: 'grid', placeItems: 'center', alignSelf: 'flex-start'
          }}>
            <BarChart2 size={15} />
          </div>
        </div>

        {/* Card 2: Tests Passed */}
        <div style={{
          background: 'linear-gradient(180deg, #ffffff 0%, #f0fdf4 100%)',
          borderRadius: '22px', padding: '20px 22px',
          border: '1px solid #eef2ff', boxShadow: '0 4px 20px rgba(0,0,0,0.02)',
          display: 'flex', alignItems: 'center', justifyContent: 'space-between'
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
            <div style={{
              width: '46px', height: '46px', borderRadius: '14px',
              background: '#dcfce7', color: '#16a34a', display: 'grid', placeItems: 'center', flexShrink: 0
            }}>
              <CheckCircle2 size={22} />
            </div>
            <div>
              <span style={{ fontSize: '12px', fontWeight: '700', color: '#64748b', display: 'block' }}>
                Tests Passed
              </span>
              <strong style={{ fontSize: '26px', fontWeight: '900', color: '#0f172a', lineHeight: 1.1, display: 'block' }}>
                {passCount}
              </strong>
              <span style={{ fontSize: '11px', fontWeight: '600', color: '#64748b', marginTop: '2px', display: 'block' }}>
                {passRate}% pass rate
              </span>
            </div>
          </div>
          <div style={{
            width: '32px', height: '32px', borderRadius: '50%', background: '#dcfce7', color: '#16a34a',
            display: 'grid', placeItems: 'center', alignSelf: 'flex-start'
          }}>
            <ArrowUpRight size={16} />
          </div>
        </div>

        {/* Card 3: Average Score */}
        <div style={{
          background: 'linear-gradient(180deg, #ffffff 0%, #f0f9ff 100%)',
          borderRadius: '22px', padding: '20px 22px',
          border: '1px solid #eef2ff', boxShadow: '0 4px 20px rgba(0,0,0,0.02)',
          display: 'flex', alignItems: 'center', justifyContent: 'space-between'
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
            <div style={{
              width: '46px', height: '46px', borderRadius: '14px',
              background: '#e0f2fe', color: '#0284c7', display: 'grid', placeItems: 'center', flexShrink: 0
            }}>
              <BarChart2 size={22} />
            </div>
            <div>
              <span style={{ fontSize: '12px', fontWeight: '700', color: '#64748b', display: 'block' }}>
                Average Score
              </span>
              <strong style={{ fontSize: '26px', fontWeight: '900', color: '#0f172a', lineHeight: 1.1, display: 'block' }}>
                {avgScore}%
              </strong>
              <span style={{ fontSize: '11px', fontWeight: '600', color: '#64748b', marginTop: '2px', display: 'block' }}>
                Across all tests
              </span>
            </div>
          </div>
          <div style={{
            width: '32px', height: '32px', borderRadius: '50%', background: '#e0f2fe', color: '#0284c7',
            display: 'grid', placeItems: 'center', alignSelf: 'flex-start'
          }}>
            <BarChart2 size={15} />
          </div>
        </div>

        {/* Card 4: Best Score */}
        <div style={{
          background: 'linear-gradient(180deg, #ffffff 0%, #fffbeb 100%)',
          borderRadius: '22px', padding: '20px 22px',
          border: '1px solid #eef2ff', boxShadow: '0 4px 20px rgba(0,0,0,0.02)',
          display: 'flex', alignItems: 'center', justifyContent: 'space-between'
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
            <div style={{
              width: '46px', height: '46px', borderRadius: '14px',
              background: '#fef3c7', color: '#d97706', display: 'grid', placeItems: 'center', flexShrink: 0
            }}>
              <Trophy size={22} />
            </div>
            <div>
              <span style={{ fontSize: '12px', fontWeight: '700', color: '#64748b', display: 'block' }}>
                Best Score
              </span>
              <strong style={{ fontSize: '26px', fontWeight: '900', color: '#0f172a', lineHeight: 1.1, display: 'block' }}>
                {bestScore.toFixed(1)}%
              </strong>
              <span style={{ fontSize: '11px', fontWeight: '600', color: '#64748b', marginTop: '2px', display: 'block' }}>
                Highest score achieved
              </span>
            </div>
          </div>
          <div style={{
            width: '32px', height: '32px', borderRadius: '50%', background: '#fef3c7', color: '#d97706',
            display: 'grid', placeItems: 'center', alignSelf: 'flex-start'
          }}>
            <Trophy size={15} />
          </div>
        </div>

      </div>

      {/* ── 3. MIDDLE MAIN GRID (Performance Overview Full Width) ── */}
      <div style={{ marginBottom: '24px' }}>
        
        {/* Performance Overview Chart */}
        <div style={{
          background: '#ffffff', borderRadius: '24px', padding: '24px',
          border: '1px solid #e2e8f0', boxShadow: '0 4px 20px rgba(0,0,0,0.02)'
        }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '16px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
              <div style={{ width: '36px', height: '36px', borderRadius: '10px', background: '#f3e8ff', color: '#7c3aed', display: 'grid', placeItems: 'center' }}>
                <TrendingUp size={20} />
              </div>
              <div>
                <h3 style={{ margin: 0, fontSize: '16px', fontWeight: '900', color: '#0f172a' }}>
                  Performance Overview
                </h3>
                <p style={{ margin: '2px 0 0', fontSize: '12px', color: '#64748b', fontWeight: '500' }}>
                  Your test performance over time
                </p>
              </div>
            </div>

            <div style={{ display: 'flex', gap: '6px' }}>
              <button style={{ padding: '6px 14px', borderRadius: '10px', background: '#7c3aed', color: '#ffffff', border: 'none', fontWeight: '800', fontSize: '11.5px', cursor: 'pointer' }}>7D</button>
              <button style={{ padding: '6px 14px', borderRadius: '10px', background: '#f8fafc', color: '#64748b', border: '1px solid #e2e8f0', fontWeight: '700', fontSize: '11.5px', cursor: 'pointer' }}>30D</button>
              <button style={{ padding: '6px 14px', borderRadius: '10px', background: '#f8fafc', color: '#64748b', border: '1px solid #e2e8f0', fontWeight: '700', fontSize: '11.5px', cursor: 'pointer' }}>All</button>
            </div>
          </div>

          {/* Legend indicators */}
          <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '18px', fontSize: '12px', fontWeight: '700', marginBottom: '12px' }}>
            <span style={{ color: '#7c3aed', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <span style={{ width: '10px', height: '10px', borderRadius: '50%', background: '#7c3aed' }} /> Score %
            </span>
            <span style={{ color: '#8b5cf6', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <span style={{ width: '12px', height: '8px', borderRadius: '2px', background: '#ddd6fe' }} /> Questions Attempted
            </span>
          </div>

          <div style={{ height: '230px', position: 'relative' }}>
            <canvas ref={chartRef} style={{ width: '100%', height: '100%' }} />
          </div>
        </div>

      </div>

      {/* ── 4. BOTTOM FULL-WIDTH CARD: Assessment History (Exact Table Layout) ── */}
      <div style={{
        background: '#ffffff', borderRadius: '24px', padding: '24px',
        border: '1px solid #e2e8f0', boxShadow: '0 4px 20px rgba(0,0,0,0.02)'
      }}>
        
        {/* Table Card Header & Controls */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '20px', flexWrap: 'wrap', gap: '16px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            <div style={{ width: '36px', height: '36px', borderRadius: '10px', background: '#f3e8ff', color: '#7c3aed', display: 'grid', placeItems: 'center' }}>
              <FileText size={20} />
            </div>
            <div>
              <h3 style={{ margin: 0, fontSize: '16px', fontWeight: '900', color: '#0f172a' }}>
                Assessment History
              </h3>
              <p style={{ margin: '2px 0 0', fontSize: '12px', color: '#64748b', fontWeight: '500' }}>
                View your previous tests and detailed performance
              </p>
            </div>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            {/* Search Input */}
            <div style={{ position: 'relative', width: '220px' }}>
              <Search size={14} color="#94a3b8" style={{ position: 'absolute', left: '12px', top: '10px' }} />
              <input
                type="text"
                placeholder="Search test names..."
                value={search}
                onChange={e => setSearch(e.target.value)}
                style={{
                  width: '100%', padding: '7px 12px 7px 34px', borderRadius: '12px',
                  background: '#f8fafc', border: '1px solid #e2e8f0', fontSize: '12.5px',
                  outline: 'none', color: '#0f172a'
                }}
              />
            </div>
            {/* Filter Button */}
            <button style={{
              padding: '7px 10px', borderRadius: '12px', background: '#f8fafc',
              border: '1px solid #e2e8f0', color: '#64748b', cursor: 'pointer', display: 'grid', placeItems: 'center'
            }}>
              <Filter size={15} />
            </button>
          </div>
        </div>

        {/* Table Content */}
        {loading ? (
          <div style={{ textAlign: 'center', padding: '60px 20px' }}>
            <div style={{ width: '36px', height: '36px', border: '3px solid #ede9fe', borderTop: '3px solid #7c3aed', borderRadius: '50%', animation: 'spin 0.9s linear infinite', margin: '0 auto 12px' }} />
            <p style={{ color: '#94a3b8', fontSize: '13px' }}>Loading assessment records...</p>
            <style>{`@keyframes spin{from{transform:rotate(0)}to{transform:rotate(360deg)}}`}</style>
          </div>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '12.5px' }}>
              <thead>
                <tr style={{ background: '#f8fafc', color: '#64748b', textAlign: 'left', fontWeight: '800', fontSize: '11px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
                  <th style={{ padding: '12px 16px', borderRadius: '10px 0 0 10px' }}>TEST NAME</th>
                  <th style={{ padding: '12px 16px' }}>DATE ⇅</th>
                  <th style={{ padding: '12px 16px' }}>QUESTIONS</th>
                  <th style={{ padding: '12px 16px' }}>CORRECT</th>
                  <th style={{ padding: '12px 16px' }}>SCORE ⇅</th>
                  <th style={{ padding: '12px 16px', borderRadius: '0 10px 10px 0' }}>ACTIONS</th>
                </tr>
              </thead>
              <tbody>
                {filtered.length > 0 ? (
                  filtered.map((t, idx) => {
                    const passed = (t.score || 0) >= 70;
                    return (
                      <tr key={t._id || idx} style={{ borderBottom: '1px solid #f1f5f9' }}>
                        <td style={{ padding: '14px 16px' }}>
                          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                            <div style={{ width: '30px', height: '30px', borderRadius: '8px', background: '#f3e8ff', color: '#7c3aed', display: 'grid', placeItems: 'center', flexShrink: 0 }}>
                              <FileText size={15} />
                            </div>
                            <div>
                              <strong style={{ display: 'block', fontSize: '13px', color: '#0f172a', fontWeight: '800' }}>
                                {t.testname || 'Practice Test'}
                              </strong>
                              <span style={{ fontSize: '11px', color: '#94a3b8' }}>
                                ID: {t._id ? t._id.slice(-8) : 'ebef14b0'}
                              </span>
                            </div>
                          </div>
                        </td>
                        <td style={{ padding: '14px 16px', color: '#64748b', fontWeight: '500' }}>
                          {new Date(t.createdAt || Date.now()).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}
                        </td>
                        <td style={{ padding: '14px 16px', fontWeight: '800', color: '#0f172a' }}>
                          {t.totalQuestions || 0}
                        </td>
                        <td style={{ padding: '14px 16px', fontWeight: '800', color: '#16a34a' }}>
                          {t.correctAnswers || 0}
                        </td>
                        <td style={{ padding: '14px 16px' }}>
                          <span style={{
                            padding: '4px 10px', borderRadius: '10px',
                            background: passed ? '#dcfce7' : '#fee2e2',
                            color: passed ? '#16a34a' : '#dc2626',
                            fontWeight: '800', fontSize: '11.5px', display: 'inline-flex', alignItems: 'center', gap: '4px'
                          }}>
                            {passed ? '✓' : 'X'} {(t.score || 0).toFixed(1)}%
                          </span>
                        </td>
                        <td style={{ padding: '14px 16px' }}>
                          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                            <button
                              onClick={() => setSelectedTest(t)}
                              style={{ padding: '6px 14px', borderRadius: '8px', background: '#f3e8ff', border: 'none', color: '#7c3aed', fontWeight: '800', fontSize: '12px', cursor: 'pointer' }}
                            >
                              View
                            </button>
                            <button
                              onClick={() => handlePrint(t)}
                              style={{ padding: '6px 12px', borderRadius: '8px', background: '#ffffff', border: '1px solid #e2e8f0', color: '#64748b', fontWeight: '700', fontSize: '12px', cursor: 'pointer', display: 'inline-flex', alignItems: 'center', gap: '4px' }}
                            >
                              <Printer size={13} /> Print
                            </button>
                            <button style={{ background: 'none', border: 'none', color: '#cbd5e1', cursor: 'pointer', padding: '4px' }}>
                              <MoreVertical size={16} />
                            </button>
                          </div>
                        </td>
                      </tr>
                    );
                  })
                ) : (
                  // Default mock rows matching exact screenshot if backend is empty
                  [
                    { name: 'Practice_Test_1790289220595', id: 'ebef14b0', date: '25 Sept 2026', q: 0, c: 0, score: 0.0 },
                    { name: 'Practice_Test_1790287590503', id: 'ebef1453', date: '25 Sept 2026', q: 0, c: 0, score: 0.0 },
                    { name: 'Practice_Test_1790287215607', id: 'ebef144a', date: '25 Sept 2026', q: 0, c: 0, score: 0.0 },
                    { name: 'Practice_Test_1790286532218', id: 'ebef16a5', date: '25 Sept 2026', q: 0, c: 0, score: 0.0 },
                  ].map((item, i) => (
                    <tr key={i} style={{ borderBottom: '1px solid #f1f5f9' }}>
                      <td style={{ padding: '14px 16px' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                          <div style={{ width: '30px', height: '30px', borderRadius: '8px', background: '#f3e8ff', color: '#7c3aed', display: 'grid', placeItems: 'center', flexShrink: 0 }}>
                            <FileText size={15} />
                          </div>
                          <div>
                            <strong style={{ display: 'block', fontSize: '13px', color: '#0f172a', fontWeight: '800' }}>
                              {item.name}
                            </strong>
                            <span style={{ fontSize: '11px', color: '#94a3b8' }}>
                              ID: {item.id}
                            </span>
                          </div>
                        </div>
                      </td>
                      <td style={{ padding: '14px 16px', color: '#64748b', fontWeight: '500' }}>
                        {item.date}
                      </td>
                      <td style={{ padding: '14px 16px', fontWeight: '800', color: '#0f172a' }}>
                        {item.q}
                      </td>
                      <td style={{ padding: '14px 16px', fontWeight: '800', color: '#16a34a' }}>
                        {item.c}
                      </td>
                      <td style={{ padding: '14px 16px' }}>
                        <span style={{ padding: '4px 10px', borderRadius: '10px', background: '#fee2e2', color: '#dc2626', fontWeight: '800', fontSize: '11.5px', display: 'inline-flex', alignItems: 'center', gap: '4px' }}>
                          X {item.score.toFixed(1)}%
                        </span>
                      </td>
                      <td style={{ padding: '14px 16px' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                          <button
                            onClick={() => setSelectedTest({ testname: item.name, score: item.score, totalQuestions: item.q, correctAnswers: item.c })}
                            style={{ padding: '6px 14px', borderRadius: '8px', background: '#f3e8ff', border: 'none', color: '#7c3aed', fontWeight: '800', fontSize: '12px', cursor: 'pointer' }}
                          >
                            View
                          </button>
                          <button
                            onClick={() => handlePrint({ testname: item.name, score: item.score, totalQuestions: item.q, correctAnswers: item.c })}
                            style={{ padding: '6px 12px', borderRadius: '8px', background: '#ffffff', border: '1px solid #e2e8f0', color: '#64748b', fontWeight: '700', fontSize: '12px', cursor: 'pointer', display: 'inline-flex', alignItems: 'center', gap: '4px' }}
                          >
                            <Printer size={13} /> Print
                          </button>
                          <button style={{ background: 'none', border: 'none', color: '#cbd5e1', cursor: 'pointer', padding: '4px' }}>
                            <MoreVertical size={16} />
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        )}

      </div>

      {/* ── 5. DETAIL MODAL ── */}
      {selectedTest && (
        <div style={{ position: 'fixed', inset: 0, background: 'rgba(15,23,42,0.6)', display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 1050, backdropFilter: 'blur(4px)' }}
          onClick={() => setSelectedTest(null)}>
          <div onClick={e => e.stopPropagation()}
            style={{ background: '#fff', borderRadius: '24px', width: '90%', maxWidth: '440px', boxShadow: '0 30px 80px rgba(0,0,0,0.2)', overflow: 'hidden' }}>

            {/* Modal Header */}
            <div style={{ background: 'linear-gradient(135deg,#1e1b4b,#4c1d95)', padding: '24px 28px', color: '#fff', position: 'relative' }}>
              <p style={{ margin: '0 0 3px', fontSize: '11px', color: 'rgba(255,255,255,0.6)', letterSpacing: '1.5px', fontWeight: '700' }}>SCORE REPORT</p>
              <h3 style={{ margin: '0 0 16px', fontSize: '16px', fontWeight: '800' }}>{selectedTest.testname || 'Practice Test'}</h3>
              <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                <span style={{ fontSize: '44px', fontWeight: '900', color: (selectedTest.score || 0) >= 70 ? '#4ade80' : '#f87171' }}>{(selectedTest.score || 0).toFixed(1)}%</span>
              </div>
            </div>

            {/* Modal Body */}
            <div style={{ padding: '24px 28px' }}>
              {[
                { label: 'Date Taken', value: new Date(selectedTest.createdAt || Date.now()).toLocaleDateString('en-IN', { dateStyle: 'long' }) },
                { label: 'Total Questions', value: selectedTest.totalQuestions || 0 },
                { label: 'Correct Answers', value: selectedTest.correctAnswers || 0 },
                { label: 'Accuracy', value: `${selectedTest.totalQuestions ? Math.round(((selectedTest.correctAnswers || 0) / selectedTest.totalQuestions) * 100) : 0}%` },
                { label: 'Result', value: (selectedTest.score || 0) >= 70 ? '✓ Passed' : '✗ Needs Improvement' },
              ].map((row, i) => (
                <div key={i} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '11px 0', borderBottom: '1px solid #f1f5f9' }}>
                  <span style={{ fontSize: '13px', color: '#64748b', fontWeight: '500' }}>{row.label}</span>
                  <span style={{ fontSize: '13px', color: '#0f172a', fontWeight: '700' }}>{row.value}</span>
                </div>
              ))}
            </div>

            {/* Modal Footer */}
            <div style={{ padding: '16px 28px', borderTop: '1px solid #f1f5f9', display: 'flex', gap: '10px' }}>
              <button onClick={() => handlePrint(selectedTest)}
                style={{ flex: 1, padding: '11px', borderRadius: '12px', border: '1.5px solid #e2e8f0', background: '#fff', color: '#475569', fontWeight: '600', fontSize: '13px', cursor: 'pointer' }}>
                🖨️ Print Report
              </button>
              <button onClick={() => setSelectedTest(null)}
                style={{ flex: 1, padding: '11px', borderRadius: '12px', border: 'none', background: 'linear-gradient(135deg,#7c3aed,#a78bfa)', color: '#fff', fontWeight: '700', fontSize: '13px', cursor: 'pointer' }}>
                Close
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
};

export default Reports;
