import React, { useState, useEffect } from 'react';
import api from '../../utils/api';

/* ─── Print Report ──────────────────────────────────────────────────────────── */
const handlePrint = (test: any) => {
  const w = window.open('', '_blank');
  if (!w) return;
  const passed = (test.score || 0) >= 70;
  w.document.open();
  w.document.write(`<!DOCTYPE html><html><head>
    <title>CSQNA Report — ${test.testname}</title>
    <style>
      *{box-sizing:border-box;margin:0;padding:0}
      body{font-family:'Segoe UI',sans-serif;padding:40px;background:#fafafa;color:#1e293b}
      .header{background:linear-gradient(135deg,#1e1b4b,#4c1d95);color:#fff;padding:36px;border-radius:16px;margin-bottom:28px}
      .header h1{font-size:26px;font-weight:800;margin-bottom:4px}
      .header p{font-size:13px;opacity:.7}
      .score{font-size:56px;font-weight:900;color:${passed?'#4ade80':'#f87171'};margin:16px 0 4px}
      .badge{display:inline-block;padding:6px 18px;border-radius:20px;font-size:13px;font-weight:700;background:${passed?'rgba(74,222,128,.15)':'rgba(248,113,113,.15)'};border:1px solid ${passed?'#4ade80':'#f87171'};color:${passed?'#4ade80':'#f87171'}}
      .grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-bottom:28px}
      .stat{background:#fff;border-radius:12px;padding:20px;border:1px solid #e2e8f0;text-align:center}
      .stat .val{font-size:32px;font-weight:800;color:#7c3aed}
      .stat .lbl{font-size:11px;font-weight:600;color:#94a3b8;text-transform:uppercase;letter-spacing:.8px;margin-top:4px}
      .footer{margin-top:28px;font-size:11px;color:#94a3b8;text-align:center}
    </style>
  </head>
  <body onload="window.print()">
    <div class="header">
      <h1>${test.testname}</h1>
      <p>CSQNA Score Report &nbsp;·&nbsp; ${new Date(test.createdAt).toLocaleDateString('en-IN',{dateStyle:'long'})}</p>
      <div class="score">${(test.score||0).toFixed(1)}%</div>
      <span class="badge">${passed?'✓ PASSED':'✗ NEEDS IMPROVEMENT'}</span>
    </div>
    <div class="grid">
      <div class="stat"><div class="val">${test.totalQuestions||0}</div><div class="lbl">Total Questions</div></div>
      <div class="stat"><div class="val">${test.correctAnswers||0}</div><div class="lbl">Correct Answers</div></div>
      <div class="stat"><div class="val">${test.totalQuestions?Math.round(((test.correctAnswers||0)/test.totalQuestions)*100):0}%</div><div class="lbl">Accuracy</div></div>
    </div>
    <div class="footer">Generated by CSQNA &nbsp;·&nbsp; csqna.com &nbsp;·&nbsp; Cybersecurity Assessment Platform</div>
  </body></html>`);
  w.document.close();
};

/* ─── Score Badge ────────────────────────────────────────────────────────────── */
const ScoreBadge: React.FC<{ score: number }> = ({ score }) => {
  const color = score >= 70 ? '#16a34a' : score >= 50 ? '#d97706' : '#dc2626';
  const bg    = score >= 70 ? '#f0fdf4' : score >= 50 ? '#fffbeb' : '#fff1f2';
  const border = score >= 70 ? '#bbf7d0' : score >= 50 ? '#fde68a' : '#fecdd3';
  return (
    <span style={{ display: 'inline-flex', alignItems: 'center', gap: '4px', padding: '5px 12px', borderRadius: '20px', background: bg, border: `1px solid ${border}`, color, fontWeight: '800', fontSize: '13px' }}>
      {score >= 70 ? '✓' : score >= 50 ? '~' : '✗'} {score.toFixed(1)}%
    </span>
  );
};

export const Reports: React.FC = () => {
  const [tests, setTests]           = useState<any[]>([]);
  const [filtered, setFiltered]     = useState<any[]>([]);
  const [search, setSearch]         = useState('');
  const [loading, setLoading]       = useState(true);
  const [selectedTest, setSelectedTest] = useState<any>(null);

  useEffect(() => {
    api.get('/user/practice/reports')
      .then(res => {
        if (res.data?.status && res.data?.data) {
          setTests(res.data.data);
          setFiltered(res.data.data);
        }
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  useEffect(() => {
    setFiltered(tests.filter(t => t.testname?.toLowerCase().includes(search.toLowerCase())));
  }, [search, tests]);

  const avgScore  = tests.length ? Math.round(tests.reduce((s, t) => s + (t.score || 0), 0) / tests.length) : 0;
  const bestScore = tests.length ? Math.max(...tests.map(t => t.score || 0)) : 0;
  const passCount = tests.filter(t => (t.score || 0) >= 70).length;

  return (
    <div style={{ maxWidth: '1080px', fontFamily: "'Inter','Segoe UI',sans-serif" }}>
      <style>{`
        @keyframes rpFadeUp { from{opacity:0;transform:translateY(16px)} to{opacity:1;transform:translateY(0)} }
        @keyframes rpPulse  { 0%,100%{opacity:.6} 50%{opacity:1} }
        .rp-row { transition: background .14s, transform .14s; border-radius:14px; }
        .rp-row:hover { background:#f8fafc !important; transform:translateX(4px); }
        .rp-card { transition: transform .2s, box-shadow .2s; }
        .rp-card:hover { transform: translateY(-3px); box-shadow: 0 10px 30px rgba(0,0,0,0.09) !important; }
        .rp-search:focus { outline:none; border-color:#7c3aed !important; box-shadow:0 0 0 3px rgba(124,58,237,.12) !important; }
      `}</style>

      {/* ── Header ── */}
      <div style={{ marginBottom: '22px', animation: 'rpFadeUp .3s ease' }}>
        <h1 style={{ margin: 0, fontSize: '22px', fontWeight: '800', color: '#0f172a' }}>Reports & Scores</h1>
        <p style={{ margin: '3px 0 0', fontSize: '13px', color: '#94a3b8' }}>Your complete assessment history and performance analytics</p>
      </div>

      {/* ── Summary Cards ── */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(170px,1fr))', gap: '14px', marginBottom: '22px' }}>
        {[
          { label: 'Total Attempts', value: tests.length, emoji: '📋', gradient: 'linear-gradient(135deg,#8b5cf6,#a78bfa)', delay: 0 },
          { label: 'Tests Passed',   value: passCount,    emoji: '✅', gradient: 'linear-gradient(135deg,#10b981,#34d399)', delay: .06 },
          { label: 'Average Score',  value: `${avgScore}%`, emoji: '📊', gradient: 'linear-gradient(135deg,#3b82f6,#60a5fa)', delay: .12 },
          { label: 'Best Score',     value: `${bestScore.toFixed(1)}%`, emoji: '🏆', gradient: 'linear-gradient(135deg,#f59e0b,#fbbf24)', delay: .18 },
        ].map((c, i) => (
          <div key={i} className="rp-card" style={{ background: '#fff', borderRadius: '18px', padding: '18px 20px', border: '1px solid #f0f2f8', boxShadow: '0 2px 12px rgba(0,0,0,0.05)', animation: `rpFadeUp .35s ease ${c.delay}s both`, position: 'relative', overflow: 'hidden' }}>
            <div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: '3px', background: c.gradient }} />
            <div style={{ fontSize: '24px', marginBottom: '8px' }}>{c.emoji}</div>
            <p style={{ margin: 0, fontSize: '28px', fontWeight: '800', color: '#0f172a', letterSpacing: '-0.5px' }}>{c.value}</p>
            <p style={{ margin: '3px 0 0', fontSize: '11px', color: '#94a3b8', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.5px' }}>{c.label}</p>
          </div>
        ))}
      </div>

      {/* ── Table Card ── */}
      <div style={{ background: '#fff', borderRadius: '20px', border: '1px solid #f0f2f8', boxShadow: '0 2px 12px rgba(0,0,0,0.05)', animation: 'rpFadeUp .4s ease .22s both', overflow: 'hidden' }}>
        {/* search bar */}
        <div style={{ padding: '20px 24px', borderBottom: '1px solid #f0f2f8', display: 'flex', alignItems: 'center', gap: '12px', flexWrap: 'wrap', justifyContent: 'space-between' }}>
          <h2 style={{ margin: 0, fontSize: '15px', fontWeight: '700', color: '#0f172a' }}>Assessment History</h2>
          <div style={{ position: 'relative' }}>
            <span style={{ position: 'absolute', left: '12px', top: '50%', transform: 'translateY(-50%)', fontSize: '14px' }}>🔍</span>
            <input type="text" placeholder="Search test names…" value={search} onChange={e => setSearch(e.target.value)}
              className="rp-search"
              style={{ paddingLeft: '34px', paddingRight: '14px', paddingTop: '9px', paddingBottom: '9px', borderRadius: '12px', border: '1.5px solid #e2e8f0', fontSize: '13px', fontFamily: 'inherit', outline: 'none', width: '240px', transition: 'border-color .2s, box-shadow .2s' }} />
          </div>
        </div>

        {loading ? (
          <div style={{ textAlign: 'center', padding: '80px 20px' }}>
            <div style={{ width: '44px', height: '44px', border: '3px solid #ede9fe', borderTop: '3px solid #7c3aed', borderRadius: '50%', animation: 'rpSpin 0.9s linear infinite', margin: '0 auto 14px' }} />
            <p style={{ color: '#94a3b8', fontSize: '13px', animation: 'rpPulse 1.4s ease infinite' }}>Extracting your assessment records…</p>
            <style>{`@keyframes rpSpin{from{transform:rotate(0)}to{transform:rotate(360deg)}}`}</style>
          </div>
        ) : filtered.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '80px 20px' }}>
            <div style={{ fontSize: '52px', marginBottom: '12px' }}>📭</div>
            <p style={{ fontWeight: '700', color: '#1e293b', marginBottom: '4px' }}>{search ? 'No results found' : 'No completed tests yet'}</p>
            <p style={{ fontSize: '13px', color: '#94a3b8' }}>{search ? 'Try a different search term.' : 'Complete your first assessment to see reports here.'}</p>
          </div>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse' }}>
              <thead>
                <tr style={{ borderBottom: '1px solid #f0f2f8' }}>
                  {['Test Name', 'Date', 'Questions', 'Correct', 'Score', 'Actions'].map((h, i) => (
                    <th key={i} style={{ padding: '13px 20px', fontSize: '11px', fontWeight: '800', color: '#94a3b8', textAlign: i >= 4 ? 'center' : 'left', letterSpacing: '0.8px', background: '#fafafa' }}>
                      {h.toUpperCase()}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {filtered.map((t, idx) => (
                  <tr key={t._id} className="rp-row" style={{ borderBottom: '1px solid #f8fafc' }}>
                    <td style={{ padding: '16px 20px' }}>
                      <p style={{ margin: 0, fontSize: '13.5px', fontWeight: '700', color: '#0f172a' }}>{t.testname}</p>
                      <p style={{ margin: '2px 0 0', fontSize: '11px', color: '#94a3b8' }}>ID: {t._id?.slice(-8)}</p>
                    </td>
                    <td style={{ padding: '16px 20px', fontSize: '13px', color: '#475569' }}>
                      {new Date(t.createdAt).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}
                    </td>
                    <td style={{ padding: '16px 20px', fontSize: '13px', fontWeight: '600', color: '#1e293b', textAlign: 'center' }}>{t.totalQuestions || 0}</td>
                    <td style={{ padding: '16px 20px', fontSize: '13px', fontWeight: '600', color: '#10b981', textAlign: 'center' }}>{t.correctAnswers || 0}</td>
                    <td style={{ padding: '16px 20px', textAlign: 'center' }}>
                      <ScoreBadge score={t.score || 0} />
                    </td>
                    <td style={{ padding: '16px 20px', textAlign: 'center' }}>
                      <div style={{ display: 'flex', gap: '6px', justifyContent: 'center' }}>
                        <button onClick={() => setSelectedTest(t)}
                          style={{ padding: '6px 14px', borderRadius: '8px', border: '1px solid #ede9fe', background: '#faf8ff', color: '#7c3aed', fontSize: '12px', fontWeight: '700', cursor: 'pointer' }}>
                          View
                        </button>
                        <button onClick={() => handlePrint(t)}
                          style={{ padding: '6px 14px', borderRadius: '8px', border: '1px solid #e2e8f0', background: '#fff', color: '#64748b', fontSize: '12px', fontWeight: '600', cursor: 'pointer' }}>
                          Print
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            <div style={{ padding: '14px 20px', borderTop: '1px solid #f0f2f8', fontSize: '12px', color: '#94a3b8', fontWeight: '500' }}>
              Showing {filtered.length} of {tests.length} records
            </div>
          </div>
        )}
      </div>

      {/* ── Detail Modal ── */}
      {selectedTest && (
        <div style={{ position: 'fixed', inset: 0, background: 'rgba(15,23,42,0.6)', display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 1050, backdropFilter: 'blur(4px)' }}
          onClick={() => setSelectedTest(null)}>
          <div onClick={e => e.stopPropagation()}
            style={{ background: '#fff', borderRadius: '24px', width: '90%', maxWidth: '440px', boxShadow: '0 30px 80px rgba(0,0,0,0.2)', animation: 'rpFadeUp .2s ease', overflow: 'hidden' }}>

            {/* Modal Header */}
            <div style={{ background: 'linear-gradient(135deg,#1e1b4b,#4c1d95)', padding: '24px 28px', color: '#fff', position: 'relative' }}>
              <p style={{ margin: '0 0 3px', fontSize: '11px', color: 'rgba(255,255,255,0.6)', letterSpacing: '1.5px', fontWeight: '700' }}>SCORE REPORT</p>
              <h3 style={{ margin: '0 0 16px', fontSize: '16px', fontWeight: '800' }}>{selectedTest.testname}</h3>
              <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                <span style={{ fontSize: '44px', fontWeight: '900', color: (selectedTest.score||0) >= 70 ? '#4ade80' : '#f87171' }}>{(selectedTest.score||0).toFixed(1)}%</span>
                <ScoreBadge score={selectedTest.score || 0} />
              </div>
            </div>

            {/* Modal Body */}
            <div style={{ padding: '24px 28px' }}>
              {[
                { label: 'Date Taken', value: new Date(selectedTest.createdAt).toLocaleDateString('en-IN', { dateStyle: 'long' }) },
                { label: 'Total Questions', value: selectedTest.totalQuestions || 0 },
                { label: 'Correct Answers', value: selectedTest.correctAnswers || 0 },
                { label: 'Accuracy', value: `${selectedTest.totalQuestions ? Math.round(((selectedTest.correctAnswers||0)/selectedTest.totalQuestions)*100) : 0}%` },
                { label: 'Result', value: (selectedTest.score||0) >= 70 ? '✓ Passed' : '✗ Needs Improvement' },
              ].map((row, i) => (
                <div key={i} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '11px 0', borderBottom: '1px solid #f1f5f9' }}>
                  <span style={{ fontSize: '13px', color: '#64748b', fontWeight: '500' }}>{row.label}</span>
                  <span style={{ fontSize: '13px', color: '#0f172a', fontWeight: '700' }}>{row.value}</span>
                </div>
              ))}
            </div>

            {/* Modal Footer */}
            <div style={{ padding: '16px 28px', borderTop: '1px solid #f1f5f9', display: 'flex', gap: '10px' }}>
              <button onClick={() => handlePrint(selectedTest)}
                style={{ flex: 1, padding: '11px', borderRadius: '12px', border: '1.5px solid #e2e8f0', background: '#fff', color: '#475569', fontWeight: '600', fontSize: '13px', cursor: 'pointer' }}>
                🖨️ Print Report
              </button>
              <button onClick={() => setSelectedTest(null)}
                style={{ flex: 1, padding: '11px', borderRadius: '12px', border: 'none', background: 'linear-gradient(135deg,#7c3aed,#a78bfa)', color: '#fff', fontWeight: '700', fontSize: '13px', cursor: 'pointer' }}>
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Reports;
